@echo off
echo Starting deployment process...
set CI=false
echo Building React app with warnings allowed...
call npm run build
echo Deploying to GitHub Pages...
call npx gh-pages -d build
echo Deployment complete!
